name: Release GitHub Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: install and build
        run: |
          npm ci
          npm run build
        env:
          CI: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
